[versions]
maven-group = "band.kessokuteatime"
archives-name = "itfollows"
mod = "1.1.0"
loader = "fabric"

minecraft = "1.20.5"
yarn = "1.20.5+build.1"
fabric-loader = "0.16.0"
fabric-api = "0.97.8+1.20.5"
fabric-loom = "1.6-SNAPSHOT"
modpublisher = "2.1.0"

# id
id-modrinth = "pLCpicf0"
id-curseforge = "998444"

# display
display-name = "It Follows!"
display-loader = "Fabric"
display-version = "1.20.5~1.20.6"

[libraries]
minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }
yarn = { group = "net.fabricmc", name = "yarn", version.ref = "yarn" }
fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric-loader" }
fabric-api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabric-api" }

[plugins]
fabric-loom = { id = "fabric-loom", version.ref = "fabric-loom" }
modpublisher = { id = "com.hypherionmc.modutils.modpublisher", version.ref = "modpublisher" }

[bundles]
fabric = ["fabric-loader", "fabric-api"]
